language: bash
services: docker

env:
  - VERSION=1.0.0
  - VERSION=1.0.0 VARIANT=alpine
  - VERSION=1.1.0
  - VERSION=1.1.0 VARIANT=alpine
  - VERSION=1.2.0
  - VERSION=1.2.0 VARIANT=alpine
  - VERSION=1.3.0
  - VERSION=1.3.0 VARIANT=alpine
  - VERSION=1.4.0
  - VERSION=1.4.0 VARIANT=alpine
  - VERSION=1.5.0
  - VERSION=1.5.0 VARIANT=alpine
  - VERSION=1.5.1
  - VERSION=1.5.1 VARIANT=alpine
  - VERSION=1.5.2
  - VERSION=1.5.2 VARIANT=alpine
  - VERSION=1.5.3
  - VERSION=1.5.3 VARIANT=alpine
  - VERSION=1.5.4
  - VERSION=1.5.4 VARIANT=alpine
  - VERSION=1.5.5
  - VERSION=1.5.5 VARIANT=alpine
  - VERSION=1.5.6
  - VERSION=1.5.6 VARIANT=alpine
  - VERSION=2.0.0
  - VERSION=2.0.0 VARIANT=alpine
  - VERSION=2.1.0
  - VERSION=2.1.0 VARIANT=alpine
  - VERSION=2.2.0
  - VERSION=2.2.0 VARIANT=alpine
  - VERSION=2.3.0
  - VERSION=2.3.0 VARIANT=alpine
  - VERSION=2.4.0
  - VERSION=2.4.0 VARIANT=alpine
  - VERSION=2.5.0
  - VERSION=2.5.0 VARIANT=alpine  
  - VERSION=2.6.0
  - VERSION=2.6.0 VARIANT=alpine  
  - VERSION=2.6.0 TAG=latest
  - VERSION=2.6.0 VARIANT=alpine TAG=latest

before_install:
  - curl -L https://goss.rocks/install | sudo sh

install:
  - git clone https://github.com/vromero/activemq-artemis-docker.git ~/activemq-artemis-docker

before_script:
  - versionTag="${VERSION}${VARIANT:+-${VARIANT}}"
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry make $versionTag 
      echo ---------------------------
      echo $TRAVIS_PULL_REQUEST
      echo $TRAVIS_BRANCH
      echo ---------------------------
      if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then travis_retry make push_$versionTag; fi
    )

